### ISSUE TITLE
“parser did not give circumfix an EXPR” after “Re-implement colon list processing” commit

### ISSUE THREAD

**Issue by AlexDaniel** [rakudo/rakudo#3000]
* [MessagePack](https://modules.perl6.org/dist/MessagePack) – Fail, Bisected: 91359141fb7501636b073ccaf6fb6598dc273bec

Error message during tests:
```
===SORRY!===
internal problem: parser did not give circumfix an EXPR
t/00-unpack.t .. 
```

**Comment by AlexDaniel** [comment]
Ping @skids

**Comment by 0racle** [comment]
The problem seems to be occurring in the return statement of `method !unpack` inside  `lib/MessagePack/Unpacker.pm6`.

There is a given/when wrapped in parens and used as a return value. Inside the given when is a check for hash key :exists. Something in there is conufising the parser.

Abbreviated version of what it looks like

```perl-6
method !unpack() {
    my $type = self!unpack-uint8;

    return (given $type {
        ...
        when (%unpack-for-type{$type}:exists) {
            %unpack-for-type{$type}(self);
        }   
        default {
            fail sprintf("Unknown type 0x%02x", $type);
        }   
    }); 
} 
```

As `given` returns a value, and it's the last thing in this method, the return is a little unidiomatic. In fact `$type` is never referred to implicitly inside the given block, so the given is redundant.

In any case, I change `return (given $type { ... }); to just `given $type { ... }`, (or remove the `given` all togther and just end the method with a string of `when` clauses and a `default` clause) the issue goes away and all MessagePack tests pass.

Also, if I leave the return statement as is, but change the condition from `when %unpack-for-type{$type}:exists` to `when (%unpack-for-type{$type}:exists)`, the issue also goes away and all  MessagePack tests pass.

At the very least, a pull-request can be made to fix MessagePack, but hopefully this info might help identify what's confusing the parser.

**Comment by 0racle** [comment]
Golfed...

```perl6
sub foo {
    (given Any {
        when %():exists { ... }
    })
}
```

**Comment by AlexDaniel** [comment]
I tried to debug this but I'm a bit confused. So `$<semilist><statement>[$semi]` does exist, but `<EXPR>` is not quite there. If I `.dump` `$<semilist><statement>[$semi]`, I get this:

```
- statement_control: when %()<>:exists { ... }
  - sym: when
  - xblock: %()<>:exists { ... }
    - pblock: { ... }
      - blockoid: { ... }
        - statementlist:  ... 
          - statement: 1 matches
            - EXPR: ... 
              - sym: ...
              - args:  
                - arglist: 
    - EXPR: :exists 
      - 0: <>
        - 0: %()
          - variable: %()
            - contextualizer: %()
              - coercee: 
                - statement:  isa NQPArray
              - sigil: %
              - sequence: 
                - statement:  isa NQPArray
        - OPER: <>
          - nibble: 
          - O: 
        - postfix_prefix_meta_operator:  isa NQPArray
        - postcircumfix: <>
          - nibble: 
          - O: 
      - OPER: 
        - O: 
      - colonpair: :exists
        - identifier: exists
      - fake_infix: 
        - O: 
```

So the expected `EXPR` is a bit deeper, but why is it looking for it at all? Could it be that `$*FAKE_INFIX_FOUND` is not reset correctly?
